apiVersion: v1
kind: Pod
metadata:
  name: deploy-admin-console-pod
  labels:
    job: deploy-service
spec:
  containers:
    - name: git
      image: alpine/git
      command: ["cat"]
      tty: true
      volumeMounts:
        - name: kaniko-workspace
          mountPath: /kaniko/workspace
          readOnly: false
    - name: helm-cli
      image: lachlanevenson/k8s-helm
      command: ["cat"]
      tty: true
      volumeMounts:
        - name: kaniko-workspace
          mountPath: /kaniko/workspace
  dnsPolicy: ClusterFirst
  dnsConfig:
    options:
      - name: ndots
        value: "1"
  volumes:
    - name: kaniko-workspace
      persistentVolumeClaim:
        claimName: jenkins-build
